# pLRG3
b1_pLRG3:
  prior:
    dist: uniform
    min:  0.0
    max:  3.0
  ref:
    dist:  norm
    loc:   1.25
    scale: 0.05
  latex: b_1^{pLRG3}
b2_pLRG3:
  prior:
    dist:  uniform
    min:   -5.0
    max:   5.0
  ref:
    dist:  norm
    loc:   0.0
    scale: 0.1
  latex: b_2^{pLRG3}
bs_pLRG3:
  # value: 0.0
  prior:
    dist:  norm
    loc:   0.0
    scale: 1
  ref:
    dist:  norm
    loc:   0
    scale: 1.0
  latex: b_s^{pLRG3}

smag_pLRG3:
  prior:
    dist:  norm
    loc:   0.974
    scale: 0.1
  ref:
    dist:  norm
    loc:   0.974
    scale: 0.05
