# pBGS2
b1_pBGS2:
  prior:
    dist: uniform
    min:  -1.0
    max:  2.0
  ref:
    dist:  norm
    loc:   1.25
    scale: 0.05
  latex: b_1^{pBGS2}
b2_pBGS2:
  prior:
    dist:  uniform
    min:   -5.0
    max:   5.0
  ref:
    dist:  norm
    loc:   0.0
    scale: 0.1
  latex: b_2^{pBGS2}
bs_pBGS2:
  # value: 0.0
  prior:
    dist:  norm
    loc:   0.0
    scale: 1
  ref:
    dist:  norm
    loc:   0
    scale: 1.0
  latex: b_s^{pBGS2}

smag_pBGS2:
  prior:
    dist:  norm
    loc:   0.8
    scale: 0.1
  ref:
    dist:  norm
    loc:   0.8
    scale: 0.05
