bsig8_LRG2:
  prior:
    dist: uniform
    min: 0.5
    max: 3.0
  ref:
    dist: norm
    loc: 1.13
    scale: 0.05
  latex: (1+b_1^{LRG2})\sigma_8
b2sig8_LRG2:
  prior:
    dist: norm
    loc: 0.0
    scale: 5
  ref:
    dist: norm
    loc: -0.1
    scale: 0.5
  latex: b_2\sigma_8^{LRG2}
bssig8_LRG2:
  prior:
    dist: norm
    loc: 0.0
    scale: 5
  ref:
    dist: norm
    loc: 0.04
    scale: 0.5
  latex: b_s\sigma_8^{LRG2}
b3sig8_LRG2:
  value: 0.0
  latex: b_3\sigma_8^{LRG2}
smag_LRG2:
  prior:
    dist: norm
    loc: 0.996
    scale: 0.1
  ref:
    dist: norm
    loc: 1.0
    scale: 0.05
B1_LRG2:
  prior:
    dist: uniform
    min: 0.0
    max: 5.0
  ref:
    dist: norm
    loc: 1.0
    scale: 0.1
  latex: B_1^{LRG2}
F_LRG2:
  prior:
    dist: uniform
    min: 0.0
    max: 5.0
  ref:
    dist: norm
    loc: 5.0
    scale: 0.1
  latex: F^{LRG2}
Sigpar_LRG2:
  prior:
    dist: norm
    loc: 0.0
    scale: 2.0
  ref:
    dist: norm
    loc: 0.0
    scale: 0.1
  latex: \Sigma_{\parallel}^{LRG2}
Sigperp_LRG2:
  prior:
    dist: norm
    loc: 0.0
    scale: 1.0
  ref:
    dist: norm
    loc: 0.0
    scale: 0.1
  latex: \Sigma_{\perp}^{LRG2}
Sigs_LRG2:
  prior:
    dist: norm
    loc: 0.0
    scale: 2.0
  ref:
    dist: norm
    loc: 2.0
    scale: 0.1
  latex: \Sigma_{s}^{LRG2}
