class: pk_likelihood_emu_fs_am_tmp2.PkLikelihood
# basedir: ./data/spec_z_dat/ #specified at frontend
linear_param_dict_fn: ./configs/params/params_linear_QSO_FS.yaml
template_fn: pk_dat/templates_QSO_desifid.txt
photo_tmp: True
zfids:
- 1.49
fs_sample_names:
- QSO
fs_datfns:
- pk_dat/Pk_QSO_desifid.txt
covfn: pk_cov/cov_rsd_QSO_desifid.txt
fs_matWfns:
- pk_wmats/wmat_QSO_desifid.txt
w_kin_fn: pk_wmats/wmat_xin_QSO_desifid.txt
fs_kmins:
- 0.02
fs_mmaxs:
- 0.2
fs_qmaxs:
- 0.2
fs_hmaxs:
- 0.0
include_priors: true
optimize: false
stop_at_error: true
cov_fac: 1.0
invcov_fac: 1.0 
#invcov_fac: 0.874
hexa: false
jeff: false